# Generated by Django 3.2.9 on 2021-12-09 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('promo', models.BooleanField(default=False)),
                ('discount', models.IntegerField(default=0)),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('promo', models.BooleanField(default=False)),
                ('discount', models.IntegerField(default=0)),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('promo', models.BooleanField(default=False)),
                ('discount', models.IntegerField(default=0)),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TankNation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a tank type', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TankType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a tank type', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TankImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tanks')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.tank')),
            ],
        ),
        migrations.AddField(
            model_name='tank',
            name='nation',
            field=models.ManyToManyField(help_text='Select a nation for this tank', to='catalog.TankNation'),
        ),
        migrations.AddField(
            model_name='tank',
            name='type',
            field=models.ManyToManyField(help_text='Select a type for this tank', to='catalog.TankType'),
        ),
        migrations.CreateModel(
            name='PremiumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='premium')),
                ('premium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.premium')),
            ],
        ),
        migrations.CreateModel(
            name='GoldImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gold')),
                ('gold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.gold')),
            ],
        ),
    ]
