# Generated by Django 3.2.9 on 2021-12-06 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gold',
            name='image',
        ),
        migrations.CreateModel(
            name='GoldImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gold')),
                ('gold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.gold')),
            ],
        ),
    ]
