# Generated by Django 3.2.9 on 2021-12-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_tanknation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold',
            name='priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='premium',
            name='priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tank',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
