# Generated by Django 3.2.9 on 2021-12-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20211209_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='tier',
            field=models.IntegerField(default=0),
        ),
    ]
