# Generated by Django 3.2.9 on 2021-12-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20211209_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tank',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='tank',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
