# Generated by Django 3.2.9 on 2021-12-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_exchangecurrency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangecurrency',
            name='name',
            field=models.CharField(help_text='enter exchange currensy', max_length=3, null=True),
        ),
    ]
