# Generated by Django 3.2.9 on 2021-12-12 19:29

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    gold = apps.get_model('catalog', 'Gold')
    premium = apps.get_model('catalog', 'Premium')
    tank = apps.get_model('catalog', 'Tank')

    for row in gold.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

    for row in premium.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

    for row in tank.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20211212_2229'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
