# Generated by Django 3.2.9 on 2021-12-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20211212_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='exchange_currensy',
        ),
        migrations.AddField(
            model_name='currency',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='currency',
            name='name',
            field=models.CharField(help_text='enter exchange currensy', max_length=3, null=True),
        ),
        migrations.DeleteModel(
            name='ExchangeCurrency',
        ),
    ]
