# Generated by Django 3.2.9 on 2021-12-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20211213_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold',
            name='main_image',
            field=models.ImageField(default='default.png', upload_to='gold/main'),
        ),
        migrations.AddField(
            model_name='premium',
            name='main_image',
            field=models.ImageField(default='default.png', upload_to='premium/main'),
        ),
        migrations.AddField(
            model_name='tank',
            name='main_image',
            field=models.ImageField(default='default.png', upload_to='tanks/main'),
        ),
    ]
