# Generated by Django 3.2.9 on 2021-12-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20211213_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanknation',
            name='icon',
            field=models.ImageField(default='default.png', upload_to='tanks/nation'),
        ),
        migrations.AddField(
            model_name='tanktype',
            name='icon',
            field=models.ImageField(default='default.png', upload_to='tanks/type'),
        ),
    ]
