# Generated by Django 3.2.9 on 2021-12-20 00:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20211215_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a product type', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='All',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('promo', models.BooleanField(default=False)),
                ('discount', models.IntegerField(default=0)),
                ('display', models.BooleanField(default=True)),
                ('priority', models.BooleanField(default=False)),
                ('tier', models.IntegerField(default=0)),
                ('main_image', models.ImageField(default='default.png', upload_to='products/main')),
                ('nation', models.ForeignKey(help_text='Select a nation for this tank', on_delete=django.db.models.deletion.CASCADE, to='catalog.tanknation')),
                ('prod_type', models.ManyToManyField(help_text='Select a type of your product', to='catalog.ProdType')),
                ('type', models.ManyToManyField(help_text='Select a type for this tank', to='catalog.TankType')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
