# Generated by Django 3.2.9 on 2021-12-20 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_all_prodtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products')),
                ('all', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.all')),
            ],
        ),
    ]
