# Generated by Django 3.2.9 on 2021-12-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_rename_all_allproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='prod_type',
            field=models.ManyToManyField(blank=True, help_text='Select a type of your product', to='catalog.ProdType'),
        ),
    ]
