# Generated by Django 3.2.9 on 2021-12-20 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('catalog', '0021_auto_20211220_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='nation',
            field=models.ForeignKey(blank=True, help_text='Select a nation for this tank', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.tanknation'),
        ),
    ]
