# Generated by Django 3.2.9 on 2021-12-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_allproducts_nation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allproducts',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='allproducts',
            name='promo',
        ),
    ]
